Problem 7 solved
BuffetWarren/projecteulertrain pull request #2
Opened 2022-12-06 21:00 UTC by BuffetWarren

I started on this branch on the evening of 06-12-2022 by solving problem 7 of euler

2022-12-07 10:37 UTC, BuffetWarren reviewed
pull Request Reviewed for improvement-wr/06-12-2022

2022-12-07 10:57 UTC, innocentTialo requested changes

2022-12-07 10:57 UTC, innocentTialo commented on src/com/warren/projecteuler/Problem7.java
> +        return  true;
Your algorithm suggest that 0 and 1 are all prime numbers! is that true?

2022-12-07 10:57 UTC, innocentTialo commented on src/com/warren/projecteuler/Problem7.java
> +    public static boolean isPrime(int n){
It is better to keep a generic algorithm like this in the Utils class so that it will be easy to use it somewhere else as you did in Problem10

2022-12-07 10:57 UTC, innocentTialo commented on src/com/warren/projecteuler/Problem7.java
> +    public static void firstPrimeNumber(int positionValue){
I think position is enough as your param name

2022-12-07 10:57 UTC, innocentTialo commented on src/com/warren/projecteuler/Problem10.java
> +    public static void sumPrimeBelowTo(int maxValueBelow) {
`public static void sumOfPrimeNumbersBelow(int number)`

2022-12-07 10:57 UTC, innocentTialo commented on src/com/warren/projecteuler/Problem10.java
> +        BigInteger sumPrimeNumber = BigInteger.valueOf(0);
`BigInteger result = BigInteger.ZERO;`

2022-12-08 07:55 UTC, BuffetWarren commented on src/com/warren/projecteuler/Problem7.java
> +        return  true;
I will modify the condition

2022-12-08 07:58 UTC, BuffetWarren commented on src/com/warren/projecteuler/Problem7.java
> +    public static boolean isPrime(int n){
Yes, that's better. It saves me from repeating

2022-12-09 07:54 UTC, merged